[<AutoOpen>]
module Posts

#load "Categories.fsx"

open System

module Path =
  let (</>) x y = IO.Path.Combine(x,y)
  let root = __SOURCE_DIRECTORY__
  let out = root </> "out"

  let outPosts = out </> "post"
  let posts = root </> "Posts"
  let media = root </> "public"
  let content = root </> "content"
  let categories = out </> "category"
  let outmedia = out </> "public"
  let outcontent = out </> "content"
  let feed = out </> "feed"
  let atom = feed </> "atom.xml"


type Post = {
    Title: string
    Category: Category 
    Date: DateTime
    Url: string}
    with
    member this.Filename =
      this.Date.ToString("yyyy-MM-dd-") + this.Url.Replace(":","")
    member this.FullUrl =
      "/post/" + this.Date.ToString("yyyy/MM/dd/") + this.Url


let date s= DateTime.Parse(s)
let posts = [
    { Title="Back in the blogosphere !"
      Category= Personal
      Date=date "2008-11-19T21:20:22Z"
      Url="Back-in-the-blogosphere" }
    { Title="'Save' is not a feature anymore"
      Category= Design
      Date=date "2008-11-19T23:00:38Z"
      Url="Save-is-not-a-feature-anymore" }
    { Title="Must know English to be a programmer ?"
      Category= Personal
      Date=date "2008-11-21T13:55:36Z"
      Url="Must-know-English-to-be-a-programmer" }
    { Title="Do you understand what it is all about ?"
      Category= Design
      Date=date "2008-11-24T14:37:26Z"
      Url="Do-you-understand-what-it-is-all-about" }
    { Title="Coincidences just happen..."
      Category= Design
      Date=date "2008-11-24T14:51:47Z"
      Url="Coincidences-just-happen" }
    { Title="CSS is too Tricky"
      Category= Design
      Date=date "2008-11-25T15:47:49Z"
      Url="CSS-is-too-Tricky" }
    { Title="Ubiquity of language... lost in translation ?"
      Category= DomainDrivenDesign
      Date=date "2008-12-01T09:49:41Z"
      Url="Ubiquity-of-language-lost-in-translation" }
    { Title="Problem with the Select N+1 problem"
      Category= Design
      Date=date "2008-12-01T15:17:04Z"
      Url="Problem-with-the-Select-N1-problem" }
    { Title="Domain Driven Design"
      Category= DomainDrivenDesign
      Date=date "2008-12-02T13:41:52Z"
      Url="Domain-Driven-Design" }
    { Title="Wow - Book review - Domain Driven Design!"
      Category= DomainDrivenDesign
      Date=date "2008-12-10T11:46:02Z"
      Url="Wow-Book-review-Domain-Driven-Design" }
    { Title="Coding and writing - The form"
      Category= Design
      Date=date "2008-12-19T15:26:43Z"
      Url="Coding-and-writing-The-form" }
    { Title="DDD: Specifications"
      Category= DomainDrivenDesign
      Date=date "2008-12-22T15:42:41Z"
      Url="DDD:-Specifications" }
    { Title="Data Structures and Algorithms"
      Category= NetFramework
      Date=date "2008-12-24T10:05:06Z"
      Url="Data-Structures-and-Algorithms" }
    { Title="Asp.Net authentication cookie oddities..."
      Category= AspNet
      Date=date "2008-12-29T17:24:12Z"
      Url="AspNet-authentication-cookie-oddities" }
    { Title="Asp.net MVC binding security issue"
      Category= AspNet
      Date=date "2009-01-08T16:58:04Z"
      Url="Aspnet-MVC-binding-security-issue" }
    { Title="Repositories and IQueryable, the paging case."
      Category= DomainDrivenDesign
      Date=date "2009-01-19T10:50:56Z"
      Url="Repositories-and-IQueryable-the-paging-case" }
    { Title="Mixing IEnumerable and IQueryable"
      Category= DomainDrivenDesign
      Date=date "2009-01-21T16:12:22Z"
      Url="Mixing-IEnumerable-and-IQueryable" }
    { Title="Lazy load and persistence ignorance"
      Category= DomainDrivenDesign
      Date=date "2009-02-07T13:44:51Z"
      Url="Lazy-load-and-persistence-ignorance" }
    { Title="Lazy loads and persistence ignorance (Part 2)"
      Category= DomainDrivenDesign
      Date=date "2009-02-08T12:17:31Z"
      Url="Lazy-loads-and-persistence-ignorance-Part-2" }
    { Title="Implement Linq to Objects in C# 2.0"
      Category= Linq
      Date=date "2009-02-17T14:55:15Z"
      Url="Implement-Linq-to-Objects-in-CSharp-2" }
    { Title="Maintenance"
      Category= NoCategory
      Date=date "2009-02-22T22:31:05Z"
      Url="Maintenance" }
    { Title="Back on track"
      Category= NoCategory
      Date=date "2009-02-23T08:55:26Z"
      Url="Back-on-track" }
    { Title="Domain Driven Design Step By Step"
      Category= DomainDrivenDesign
      Date=date "2009-02-24T14:57:58Z"
      Url="Domain-Driven-Design-Step-By-Step" }
    { Title="How *not* to inject services in entities"
      Category= DomainDrivenDesign
      Date=date "2009-03-04T15:01:53Z"
      Url="How-not-to-inject-services-in-entities" }
    { Title="QCon London 2009"
      Category= DomainDrivenDesign
      Date=date "2009-03-12T15:21:23Z"
      Url="QCon-London-2009" }
    { Title="Back on Repositories and Paging. Introducing reporting."
      Category= DomainDrivenDesign
      Date=date "2009-04-08T12:10:43Z"
      Url="Back-on-Repositories-and-Paging-Introducing-reporting" }
    { Title="TDD becomes Design By Example"
      Category= Agile
      Date=date "2009-04-18T08:22:08Z"
      Url="TDD-becomes-Design-By-Example" }
    { Title="Geek balance... or not !"
      Category= Personal
      Date=date "2009-04-28T21:04:53Z"
      Url="Geek-balancehellip-or-not" }
    { Title="Strategic Design"
      Category= DomainDrivenDesign
      Date=date "2009-04-28T21:34:37Z"
      Url="Strategic-Design" }
    { Title="Decimal, what are those trailing zeros ?"
      Category= NetFramework
      Date=date "2009-05-07T10:24:17Z"
      Url="Decimal-what-are-those-trailing-zeros" }
    { Title="IOC Container, Go Hide !"
      Category= Design
      Date=date "2009-05-15T10:10:28Z"
      Url="IOC-container-go-hide" }
    { Title="IOC Container, Go Hide (part 2)"
      Category= Design
      Date=date "2009-05-19T13:29:11Z"
      Url="IOC-Container-Go-Hide-part-2" }
    { Title="Met Eric Evans at ParisJug"
      Category= DomainDrivenDesign
      Date=date "2009-06-16T21:58:28Z"
      Url="Met-Eric-Evans-at-ParisJug" }
    { Title="When DDD should be considered ?"
      Category= DomainDrivenDesign
      Date=date "2009-06-16T22:11:23Z"
      Url="When-DDD-should-be-considered" }
    { Title="Which model is best ? Thats not the question."
      Category= DomainDrivenDesign
      Date=date "2009-06-17T13:56:52Z"
      Url="Which-model-is-best-Thats-not-the-question" }
    { Title="Strategic Design at DDD Exchange"
      Category= DomainDrivenDesign
      Date=date "2009-06-19T12:05:27Z"
      Url="Strategic-Design-at-DDD-Exchange" }
    { Title="Where are my Entities and my Repositories ?"
      Category= DomainDrivenDesign
      Date=date "2009-06-23T12:20:11Z"
      Url="Where-are-my-Entities-and-my-Repositories" }
    { Title="Distributed Domain Driven Design and Aggregates"
      Category= DomainDrivenDesign
      Date=date "2009-06-23T14:59:07Z"
      Url="Distributed-Domain-Driven-Design-and-Aggregates" }
    { Title="DDD and Code ReUse"
      Category= DomainDrivenDesign
      Date=date "2009-07-24T14:34:22Z"
      Url="DDD-and-Code-ReUse" }
    { Title="C# Static interfaces"
      Category= NetFramework
      Date=date "2009-10-21T12:46:26Z"
      Url="CSharp-Static-interfaces" }
    { Title="C# Static interfaces - Take 2"
      Category= NetFramework
      Date=date "2009-10-22T13:11:07Z"
      Url="CSharp-Static-interfaces-Take-2" }
    { Title="Uniqueness validation in CQRS Architecture"
      Category= DomainDrivenDesign
      Date=date "2009-10-28T14:05:36Z"
      Url="Uniqueness-validation-in-CQRS-Architecture" }
    { Title="Event Sourcing and CQRS, Now !"
      Category= DomainDrivenDesign
      Date=date "2009-10-30T14:53:50Z"
      Url="Event-Sourcing-and-CQRS-Now" }
    { Title="Event Sourcing and CQRS, Let's use it."
      Category= DomainDrivenDesign
      Date=date "2009-11-02T14:45:16Z"
      Url="Event-Sourcing-and-CQRS-Lets-use-it" }
    { Title="Event Sourcing and CQRS, Dispatch options."
      Category= DomainDrivenDesign
      Date=date "2009-11-03T14:41:10Z"
      Url="Event-Sourcing-and-CQRS-Dispatch-options" }
    { Title="Event Sourcing and CQRS, Serialization"
      Category= DomainDrivenDesign
      Date=date "2009-11-05T13:00:38Z"
      Url="Event-Sourcing-and-CQRS-Serialization" }
    { Title="Udi Dahan talks on CQRS at Zenika"
      Category= DomainDrivenDesign
      Date=date "2009-11-16T10:08:51Z"
      Url="Udi-Dahan-talks-on-CQRS-at-Zenika" }
    { Title="Udi Dahan talks on CQRS in Paris"
      Category= DomainDrivenDesign
      Date=date "2009-11-17T15:37:23Z"
      Url="Udi-Dahan-talks-on-CQRS-in-Paris" }
    { Title="Udi Dahan's post on CQRS"
      Category= DomainDrivenDesign
      Date=date "2009-12-10T09:15:48Z"
      Url="Udi-Dahan-post-on-CQRS" }
    { Title="Business Errors are Just Ordinary Events"
      Category= DomainDrivenDesign
      Date=date "2009-12-10T13:31:24Z"
      Url="Business-Errors-are-Just-Ordinary-Events" }
    { Title="Event Sourcing and CQRS, Snapshots !"
      Category= DomainDrivenDesign
      Date=date "2010-02-25T09:38:23Z"
      Url="Event-Sourcing-and-CQRS-Snapshots" }
    { Title="Event Sourcing and CQRS, Bounded Contexts"
      Category= DomainDrivenDesign
      Date=date "2010-04-17T13:21:42Z"
      Url="Event-Sourcing-and-CQRS-Bounded-Contexts" }
    { Title="Event Sourcing and CQRS, Events Deserialization"
      Category= DomainDrivenDesign
      Date=date "2010-04-25T20:51:14Z"
      Url="Event-Sourcing-and-CQRS-Events-Deserialization" }
    { Title="DDD Exchange 2010"
      Category= DomainDrivenDesign
      Date=date "2010-06-14T08:58:29Z"
      Url="DDD-Exchange-2010" }
    { Title="Duck : Delete Update Create Killer"
      Category= Duck
      Date=date "2010-10-18T23:49:18Z"
      Url="Duck-Delete-Update-Create-Killer" }
    { Title="Code code code"
      Category= NetFramework
      Date=date "2011-01-20T11:07:57Z"
      Url="Code-code-code" }
    { Title="SmtpListener"
      Category= NetFramework
      Date=date "2011-01-21T13:45:00Z"
      Url="SmtpListener" }
    { Title="Switching keyboard language in WP7"
      Category= WP7
      Date=date "2011-01-24T10:36:24Z"
      Url="Switching-keyboard-language-in-WP7" }
    { Title="Time"
      Category= DomainDrivenDesign
      Date=date "2011-06-08T22:54:17Z"
      Url="Time" }
    { Title="DDDx 2011"
      Category= DomainDrivenDesign
      Date=date "2011-06-14T08:30:46Z"
      Url="DDDx-2011" }
    { Title="Event Sourcing and CQRS, Dispatch options 2"
      Category= DomainDrivenDesign
      Date=date "2011-06-21T08:38:57Z"
      Url="Event-Sourcing-and-CQRS,-Dispatch-options-2" }
    { Title="I love SQL Server and cultures... NOT !"
      Category= NetFramework
      Date=date "2011-12-02T10:14:15Z"
      Url="I-love-SQL-Server-and-cultures-NOT" }
    { Title="NuRep your local NuGet+symbols+source repository"
      Category= NuRep
      Date=date "2012-02-26T10:25:03Z"
      Url="NuRep-your-local-NuGetsymbolssource-repository" }
    { Title="Caching done right"
      Category= CQRS
      Date=date "2012-03-05T12:49:38Z"
      Url="Caching-done-right" }
    { Title="Make it simpler : get rid of Mocking Fx"
      Category= Design
      Date=date "2012-06-14T12:32:45Z"
      Url="Make-it-simpler-:-get-rid-of-Mocking-Fx" }
    { Title="SimpleCQRS the F# version"
      Category= CQRS
      Date=date "2012-06-21T21:57:27Z"
      Url="SimpleCQRS-the-F-version" }
    { Title="Entities and Repository injection - follow up"
      Category= DomainDrivenDesign
      Date=date "2013-03-03T21:27:37Z"
      Url="Entities-and-Repository-injection-ndash;-follow-up" }
    { Title="Time is Money! DevoxxFr"
      Category= NoCategory
      Date=date "2013-04-03T08:24:43Z"
      Url="Time-is-Money!-DevoxxFr" }
    { Title="C# Static interfaces - Take 3"
      Category= FSharp
      Date=date "2013-04-03T22:09:52Z"
      Url="C-Static-interfaces-Take-3" }
    { Title="C# Static interfaces - Take 3 - redirect"
      Category= FSharp
      Date=date "2013-04-04T12:37:56Z"
      Url="C-Static-interfaces-ndash;-Take-3" }
    { Title="Event Sourcing vs Command Sourcing"
      Category= EventSourcing
      Date=date "2013-07-27T23:00:11Z"
      Url="Event-Sourcing-vs-Command-Sourcing" }
    { Title="Command Events and Context"
      Category= DomainDrivenDesign
      Date=date "2013-07-28T22:12:13Z"
      Url="Command-Events-and-Context" }
    { Title="Generalized Conway's law"
      Category= Design
      Date=date "2013-12-17T09:09:51Z"
      Url="Generalized-Conway-s-law" }
    { Title="Event Sourcing. Draw it"
      Category= NoCategory
      Date=date "2014-01-04T21:58:05Z"
      Url="Event-Sourcing.-Draw-it" }
    { Title="Monoidal Event Sourcing"
      Category= EventSourcing
      Date=date "2014-04-11T02:34:48Z"
      Url="Monoidal-Event-Sourcing" }
    { Title="Monoidal Event Sourcing Examples"
      Category= EventSourcing
      Date=date "2014-04-27T00:16:49Z"
      Url="Monoidal-Event-Sourcing-Examples" }
    { Title="Speaking computers for more fun !"
      Category= FSharp
      Date=date "2014-12-23T10:17:32Z"
      Url="Speaking-computers-for-more-fun-!" }
    { Title="Ukulele Fun for XMas !"
      Category= FSharp
      Date=date "2015-12-17T09:44:43Z"
      Url="Ukulele-Fun-for-XMas-!" }
    { Title="fck: Fake Construction Kit"
      Category= FSharp
      Date=date "2016-12-04T09:34:56Z"
      Url="fck:-Fake-Construction-Kit" }
    { Title="Back to blogging"
      Category = Category.Personal
      Date=date "2018-01-20T22:04:08Z"
      Url="back-to-blogging" }
    { Title="Functional Core"
      Category = Category.Design
      Date=date "2018-01-25T21:41:12Z"
      Url="functional-core" }
    { Title="Functional Core - Part 2"
      Category = Category.Design
      Date=date "2018-02-01T21:09:13Z"
      Url="functional-core-2" }
    { Title="Information Space-Time"
      Category = Category.Design
      Date=date "2018-03-11T14:33:56Z"
      Url="information-space-time" }
    { Title="OpenFSharp 2018"
      Category = Category.FSharp
      Date=date "2018-09-28T21:14:46Z"
      Url="openfsharp-2018" }
    { Title="10 years"
      Category = Category.Personal
      Date=date "2018-11-19T13:40:02Z"
      Url="10-years" }
    { Title="Full F# Blog"
      Category = Category.FSharp
      Date=date "2018-12-07T08:04:00Z"
      Url="full-fsharp-blog" }
    { Title="Full F# Blog - Part 2"
      Category = Category.FSharp
      Date=date "2018-12-09T15:30:06Z"
      Url="full-fsharp-blog-2" }
]

